# Configuration for nethxeumd
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'nethxeumd --help' for all available options.

data-dir=/var/lib/nethxeum
log-file=/var/log/nethxeum/nethxeum.log
log-level=0
